_target_: uncertainty_modeling.data.torch_dataloader.BaseDataModule   # Base Data Module
num_classes: 24
ignore_index: 255
num_workers: 10
batch_size: 6
val_batch_size: 6
data_fold_id: 0
augmentations: ${AUGMENTATIONS}
evaluate_training_data: ${evaluate_training_data}
dataset:
  _target_: uncertainty_modeling.data.cityscapes_dataset.Cityscapes_dataset
  splits_path: "${data_input_dir}/splits/firstCycle/splits.pkl"