_target_: uncertainty_modeling.data.torch_dataloader.BaseDataModule   # Base Data Module
num_classes: 2
ignore_index: -1
num_workers: 8
batch_size: 16
val_batch_size: 16
data_fold_id: 0
augmentations: ${AUGMENTATIONS}
evaluate_training_data: ${evaluate_training_data}
evaluate_all_raters: ${evaluate_all_raters}
dataset:
  _target_: uncertainty_modeling.data.lidc2d_dataset.LIDC2DDataset
  splits_path: "/home/jloch/Desktop/diff/luzern/values_datasets/lidc_2d_small/splits/texture/firstCycle/splits.pkl"
