_target_: uncertainty_modeling.data.torch_dataloader.BaseDataModule   # Base Data Module
num_classes: 2
ignore_index: -1
num_workers: 8
batch_size: 16
val_batch_size: 16
data_fold_id: 0
augmentations: ${AUGMENTATIONS}
evaluate_training_data: ${evaluate_training_data}
dataset:
  _target_: uncertainty_modeling.data.lidc2d_dataset.LIDC2DDataset
  splits_path: "${data_input_dir}/splits/texture/firstCycle/splits.pkl"
