# @package _global_
defaults:
  - _self_
  - datamodule: gta
  - model: hrnet_ssn
  - data_augmentations: tta_gta

exp_name: "gta-ssn"
version: null
ckpt_path: null

dataset: "gta"
data_input_dir: "/home/jloch/Desktop/diff/luzern/values_datasets/${dataset}"
save_dir: "/home/jloch/Desktop/diff/luzern/values/saves"

seed: 123
pretrain_epochs: 5
batch_size: 6
evaluate_training_data: true

# training hyperparams
learning_rate: 0.0001
weight_decay: 0.0005

optimizer:
  _target_: torch.optim.RMSprop
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  momentum: 0.6
  # alpha: 0.9

lr_scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  power: 0.9

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}

progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10

trainer:
  max_epochs: 300
  accelerator: gpu
  devices: 1
  precision: 32 # bf16-mixed
  # deterministic: true 
  # gradient_clip_val: 0.0
  # gradient_clip_algorithm: norm
  # log_every_n_steps: 50
  # check_val_every_n_epoch: 1
  full_last_ckpt: true
  shutdown_timer: 82800 # 23 hours
  do_shutdown: false