#@package _global_
QUANTILE:
  datasets: ["val"]
  accumulated: True
  function:
    _target_: evaluation.uncertainty_aggregation.find_threshold.get_foreground_quantile
  postprocess_function:
    _target_: evaluation.uncertainty_aggregation.find_threshold.save_foreground_quantiles
THRESHOLD:
  datasets: ["val"]
  accumulated: True
  function:
    _target_: evaluation.uncertainty_aggregation.find_threshold.threshold_images_paths
  postprocess_function:
    _target_: evaluation.uncertainty_aggregation.find_threshold.find_threshold