#@package _global_
defaults:
  - /../../uncertainty_modeling/configs/datamodule/lidc_2d_small@LIDC.datamodule_config
  - /../../uncertainty_modeling/configs/data_augmentations/tta_lidc_2d_small
  - _self_

augment_mult: null

LIDC:
  iter_params:
    shift: [ "texture" ]
    pred_model: [ "SSN" ]
    seed: [ "120" ]
    version: [ "aug0_s125" ] #[ "aug0_s12[0,1,2,3,4]" ]
    epochs: [ 10, 13, 17, 22, 28, 37, 48, 62, 81, 105, 136, 176, 229, 297, 385, 500 ]
    ema: [ "_ema" ]
  fold: 0
  rank: 5
  image_ending: ".png"
  unc_ending: ".tif"
  n_reference_segs: 4
  evaluate_training_data: ${evaluate_training_data}
  datamodule_config:
    data_input_dir: "/home/jloch/Desktop/diff/luzern/values_datasets/lidc_2d_small"

  prediction_models:
    Softmax:
      naming_scheme_version: "{shift}_fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty" ]
      aggregations: [ "patch_level", "threshold" ]
    Dropout:
      naming_scheme_version: "{shift}_fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "patch_level", "threshold" ]
    Ensemble:
      naming_scheme_version: "{shift}_fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "patch_level", "threshold" ]
    TTA:
      naming_scheme_version: "{shift}_fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "patch_level", "threshold" ]
    SSN:
      naming_scheme_pred_model: "lidc-small-ssn-OF-mini"
      naming_scheme_version: "{version}/e{epochs}{ema}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "patch_level", "threshold" ]