# @package _global_
model:
  nickname: "dropout"
  _target_: uncertainty_modeling.unc_mod_utils.model_factory.instantiate_network
  target: ${network.target}
  cfg: ${network.cfg}
  overrides:
    MODEL:
      PRETRAINED: true
      EXTRA:
        DROPOUT_FINAL: true
