# @package _global_
model:
  nickname: "softmax"
  _target_: uncertainty_modeling.unc_mod_utils.model_factory.instantiate_network
  target: ${network.target}
  cfg: ${network.cfg}
  overrides:
    MODEL:
      SSN: false
