# @package _global_
model:
  _target_: uncertainty_modeling.global_utils.model_factory.instantiate_network
  target: ${network.target}
  cfg: ${network.cfg}
  overrides:
    MODEL:
      SSN: true
      SSN_RANK: 10
      SSN_EPS: 1e-5
