# @package _global_
eu_method:
  name: "dropout"
  nickname: "eu=dropout"

dropout:
  enabled: true
  probability: 0.2

model:
  overrides:
    MODEL:
      PRETRAINED: true
  dropout_cfg: ${dropout}
