# @package _global_
eu_method:
  name: "swag_diag"
  nickname: "eu=swag_diag"

model:
  overrides:
    MODEL:
      SWAG: true

swag:
  enabled: true
  snapshot_frequency: 1
  max_snapshots: 30
  min_variance: 1e-30
  diag_only: true
